#!/bin/bash
#
## A simple script to start a dzen bar to display conky

name=${0##*/}
width=800
height=12
screens=1
fs=10
conkyconf=""

function print_help() {
    echo "usage: $name [options]

optional args:

    -w|--width    the width of the bar. Default is $width
       --height   the height of the bar. Default is $height
    -f|--fontsize the font size. Default is $fs
    -c|--config   specify alternate conky config. Defaults to conky default.
    -h|--help     print this help."
}

pretend=0
OPTS=$(getopt -o w:f:c:h --long width:,fontsize:,config:,height:,help -n "$name" -- "$@")

if [[ $? != 0 ]]; then echo "option error" >&2; exit 1; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -w|--width)
            width="$2"
            shift 2;;
        -f|--fontsize)
            fs="$2"
            shift 2;;
        -c|--config)
            conkyconf="-c $2"
            shift 2;;
        --height)
            height="$2";
            shift 2;;
        -h|--help)
            print_help
            exit 0
            ;;
        --)
            shift; break;;
        *)
            echo "Internal error!"; exit 1;;
    esac
done

screens=$(xrandr | grep '*' | cut -f 4 -d ' ')

sn=1
for screen in $screens; do
    xres=${screen%x*}
    xpos=$(echo "$xres-$width" | bc -l)
    conky $conkyconf 2>/dev/null | dzen2 -ta r -sa r -x $xpos -h $height -y 1 -w $width -bg '#000000' -fg '#a1a1a1' -fn "Terminus:style=Regular:pixelsize=$fs:antialias=true" -e 'button3=lower;sigusr1=raise' -xs $sn &
    let sn+=1
done
