#!/bin/bash
#
## A simple script to start a dzen bar to display conky

name=${0##*/}
width=800
screens=1

function print_help() {
    echo "usage: $name [options]

optional args:

    -w|--width    the width of the bar. Default is 860.
    -h|--help     print this help."
}

pretend=0
OPTS=$(getopt -o w:h --long width:,help -n "$name" -- "$@")

if [ $? != 0 ]; then echo "option error" >&2; exit 1; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -w|--width)
            width="$2"
            shift 2;;
        -h|--help)
            print_help
            exit 0
            ;;
        --)
            shift; break;;
        *)
            echo "Internal error!"; exit 1;;
    esac
done

screens=$(xrandr | grep '*' | cut -f 4 -d ' ' | sort -r)

sn=1
for screen in $screens; do
    xres=${screen%x*}
    xpos=$(echo "$xres-$width" | bc -l)
    echo $xpos $width
    conky 2>/dev/null | dzen2 -x $xpos -w $width -bg '#000000' -fg '#a1a1a1' -fn 'Terminus:style=Regular:pixelsize=10:antialias=true' -e '' -xs $sn &
    let sn+=1
done
