#!/bin/bash
#
## A simple script to start a dzen bar to display conky

name=${0##*/}
xpos=500
width=860

function print_help() {
    echo "usage: $name [options]

optional args:

    -x|--xpos   the starting x position of the bar. Default is 500.
    -w|--width  the width of the bar. Default is 860.
    -h|--help   print this help."
}

pretend=0
OPTS=$(getopt -o x:w:h --long xpos:,width:,help -n "$name" -- "$@")

if [ $? != 0 ]; then echo "option error" >&2; exit 1; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -x|--xpos)
            xpos="$2"
            shift 2;;
        -w|--width)
            width="$2"
            shift 2;;
        -h|--help)
            print_help
            exit 0
            ;;
        --)
            shift; break;;
        *)
            echo "Internal error!"; exit 1;;
    esac
done

conky | dzen2 -ta r -x $xpos -w $width -bg '#000000' -fg '#a1a1a1' -fn '-*-terminus-*-*-*-*-12-*-*-*-*-*-iso8859' -e '' &
