#!/usr/bin/env bash

name=${0##*/}

function die() {
    echo $1
    cleanup
    exit -1
}

function cleanup() {
    rm -f /tmp/$runtimetar
}

function print_help() {
    echo "usage: $name [options]

optional args:

    -h|--help     print this help."
}

pretend=0
runtimetar=steam-runtime-sdk_latest.tar.xz
opt_dir="$HOME/opt/"
runtime_dir="steam-runtime-sdk_2013-09-05"

OPTS=$(getopt -o h --long help -n "$name" -- "$@")

if [[ $? != 0 ]]; then echo "option error" >&2; exit 1; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -h|--help)
            print_help
            exit 0
            ;;
        --)
            shift; break;;
        *)
            echo "Internal error!"; exit 1;;
    esac
done

if [[ ! -d "$opt_dir/$runtime_dir" ]]; then
    mkdir -p $opt_dir || die "unable to create opt dir"
    echo "Downloading runtime"
    wget http://media.steampowered.com/client/runtime/${runtimetar} -O /tmp/${runtimetar} || die "unable to download runtime tar"
    echo "Unpacking runtime"
    tar xf /tmp/${runtimetar} -C $opt_dir || die "unable to unpack runtime"
    cleanup
fi

pushd "$opt_dir/$runtime_dir" &> /dev/null
echo "Setting up runtime"
./setup.sh --host=$host_arch --target='i386 amd64' --release --auto-update || die "unable to install runtime"
popd &> /dev/null
