#!/usr/bin/env bash

width=360
screen=$(xrandr | grep '*' | cut -f 4 -d ' ')
xres=${screen%x*}
xpos=$(echo "$xres-$width" | bc -l)

host=$(uname -n)
kernel=$(uname -r)
uptime=$(uptime | sed 's/.* up //' | sed 's/[0-9]* us.*//' | sed 's/ day, /d /' \
         | sed 's/ days, /d /' | sed 's/:/h /' | sed 's/ min//' \
         |  sed 's/,/m/' | sed 's/  / /')

(
echo "System Information"
echo "Host: $host "
echo "Kernel: $kernel"
echo "Uptime: $uptime "
) | dzen2 -p \
    -x $xpos -y 26 \
    -w $width \
    -l 3 -sa l -ta c \
    -bg '#262626' \
    -fg '#bcbcbc' \
    -fn "Terminus:style=Regular:pixelsize=24:antialias=true" \
    -title-name 'sysinfo_batinfo' \
    -e 'onstart=uncollapse;button1=exit;button3=exit'
