#!/usr/bin/env bash
#
## A simple script to manage a rotating background image.
## Create ~/.wallpaper and place the desired backgrounds into the directory.
## Or symlink ~/.wallpaper to a directory with backgrounds.

name=${0##*/}
duration=15m
mode="--bg-fill"
additional_opts=""

function print_help() {
    echo "usage: $name [options]

optional args:

    -d|--duration amount of time until wallpaper change. Default is 15m.
    -m|--mode     background mode. Default is fill.
    --no-xinerama disable xinerama. Useful for very large backgrounds that should span multiple monitors.
    -h|--help     print this help."
}

pretend=0
OPTS=$(getopt -o d:m:h --long duration:,mode:,no-xinerama,help -n "$name" -- "$@")

if [[ $? != 0 ]]; then echo "option error" >&2; exit 1; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -d|--duration)
            duration="$2"
            shift 2;;
        -m|--mode)
            mode="--bg-$2"
            shift 2;;
        --no-xinerama)
            additional_opts='--no-xinerama';
            shift;;
        -h|--help)
            print_help
            exit 0
            ;;
        --)
            shift; break;;
        *)
            echo "Internal error!"; exit 1;;
    esac
done

while true; do
    feh $mode $additional_opts $(find $HOME/.wallpaper/ -type f -exec file {} \; | awk -F: '{ if ($2 ~/image/) print $1}' | shuf -n 1)
    sleep $duration
done &

